Models/Application.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WeCount.Models
{
    public partial class Application
    {
        [Key]
        public int Id { get; set; }
        [Required, StringLength(25, MinimumLength = 1)]
        [Display(Name = "Prénom")]
        [RegularExpression("^[a-zA-Z0-9 ]+$")]
        public string FirstName { get; set; }
        [Required, StringLength(25, MinimumLength = 1)]
        [Display(Name = "Nom")]
        [RegularExpression("^[a-zA-Z0-9 ]+$")]
        public string LastName { get; set; }

        public string Slag { get; set; }

        [Required]
        [EmailAddress]
        public string Mail { get; set; }
        [Required]
        [Display(Name = "Téléphone")]
        public string Phone { get; set; }
        [Required]
        [Display(Name = "Niveau D'etude")]
        public string StudyLevel { get; set; }

        [Range(1, 100)]
        [Display(Name = "Nombre d’années d’expérience")]
        public int YearsOfExperinces { get; set; }
        [Required]
        [Display(Name = "Dernier employeur")]
        public string LastJob { get; set; }

        [Display(Name = "CV")]
        public string Resume { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;
    }

    public partial class Application
    {
        [NotMapped]
        public string FullName => $"{FirstName} {LastName}";

        public string GetExtension()
        {
            string extension = Resume.Substring(Resume.LastIndexOf("."));
            return extension;
        }
    }
}

Controllers/ApplicationsController.cs
using System;
using System.IO;
using System.Collections.Generic;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Net.Http.Headers;

using WeCount.Data.Services;
using WeCount.Data.ViewModels;
using WeCount.Models;

namespace WeCount.Controllers
{
    [Route("/")]
    public class ApplicationsController : Controller
    {
        private readonly ApplicationsService _applicationsService;
        public ApplicationsController(ApplicationsService applicationsService)
        {
            this._applicationsService = applicationsService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("apply")]
        public IActionResult Apply()
        {
            return View();
        }

        [HttpGet("applications")]
        public IActionResult Applications()
        {
            // List<Application> _applications = _applicationsService.GetEntities();

            ViewBag.Applications = _applicationsService.GetEntities();
            return View();
        }

        [HttpPost("apply")]
        [ValidateAntiForgeryToken]
        public IActionResult Apply([Bind("FirstName, LastName, Mail, Phone, StudyLevel, YearsOfExperinces, LastJob")]Application application)
        {
            if (ModelState.IsValid)
            {
                Application _application = _applicationsService.InsertEntity(application);

                string slag = _application.Slag;
                return Redirect($"/apply/resume/{slag}");
            }
            else
            {
                return View();
            }
        }

        [HttpGet("apply/resume/{slag}")]
        public IActionResult ApplyResume(string slag)
        {
            return View();
        }

        [HttpPost("apply/resume/{slag}")]
        [ValidateAntiForgeryToken]
        public IActionResult ApplyResume([Bind("ResumeFile")]ResumeVM resumeVM, string slag, [FromServices] IWebHostEnvironment webHostEnvironment)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = UploadedFile(resumeVM, slag, webHostEnvironment);
                _applicationsService.InsertResume(slag, uniqueFileName);
                return Redirect($"/application/details/{slag}");
            }
            else
            {
                return View();
            }
        }

        [HttpGet("display/application/{slag}")]
        public IActionResult DisplayApplication(string slag)
        {
            Application _application = _applicationsService.GetEntity(slag);
            return View(_application);
        }

        [HttpGet("application/details/{slag}")]
        public IActionResult ApplicationDetails(string slag)
        {
            Application _application = _applicationsService.GetEntity(slag);
            return View(_application);
        }

        private string UploadedFile(ResumeVM resumeVM, string slag, IWebHostEnvironment webHostEnvironment)
        {
            string relativePath = "";
            if (resumeVM.ResumeFile != null)
            {
                var _uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, $"Resumes\\{slag}");
                if (!Directory.Exists(_uploadsFolder))
                {
                    Directory.CreateDirectory(_uploadsFolder);
                }

                string filePath = Path.Combine(_uploadsFolder, resumeVM.ResumeFile.FileName);
                relativePath = Path.Combine($"Resumes\\{slag}", resumeVM.ResumeFile.FileName);
                using (FileStream fileStream = new FileStream(filePath, FileMode.Create))
                {
                    resumeVM.ResumeFile.CopyTo(fileStream);
                }
            }

            return relativePath;
        }

        [HttpPost("application/delete/{slag}")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteApplication(string slag)
        {
            _applicationsService.DeleteEntity(slag);
            return Redirect("/applications");
        }

        [HttpPost("application/search")]
        [ValidateAntiForgeryToken]
        public IActionResult SearchApplications(SearchVM searchVM)
        {
            if (ModelState.IsValid)
                ViewBag.Applications = _applicationsService.SearchEntity(searchVM.SearchText);
            else
                ViewBag.Applications = _applicationsService.GetEntities();

            return View("~/Views/Applications/Applications.cshtml");
        }
    }
}

Views/Applications/ApplicationDetails.cshtml
@model WeCount.Models.Application

@{
    ViewData["Title"] = "Condidat Détails";
}

@section styles {
    <style>
        .grid {
            display: grid;
            grid-template-columns: 1fr 3fr;
            gap: 8px;
            font-size: 18px
        }

        object, img {
            width: 100%;
            display: block;
            min-height: 600px
        }

        h4 {
            margin: 0;
            padding: 4px 0
        }

        strong {
            font-weight: 600;
            margin: 14px 0;
            color: #1d1c1c;
            display: block;
        }

        p {
            color: var(--grey-color);
            padding: 0;
            margin: 7px 0;
            line-height: 1.4
        }

        .padding-left {
            display: block;
            padding-left: 18px;
        }
    </style>
}

<div class="container content-container">
    <div><strong style="display: inline">• Étape 1 / Étape 2 / Étape 3 :</strong> visualisation du résumé des informations saisies.</div>
    <br />
    <div class="grid">
        <div>
            <h4>Nom: <span class="padding-left">@Model.LastName</span></h4>
            <h4>Préom: <span class="padding-left">@Model.FirstName</span></h4>
            <strong>Mail: <span class="padding-left">@Model.Mail</span></strong>
            <strong>Téléphone: <span class="padding-left">@Model.Phone</span></strong>

            <strong>
                Nombre d’années d’expérience:
                <span class="padding-left">
                @Model.YearsOfExperinces
                @if (Model.YearsOfExperinces == 1)
                {
                    <span>année</span>
                }
                else if (Model.YearsOfExperinces >= 1)
                {
                    <span>années</span>
                }
                </span>
            </strong>

            <p class="card-text three-lines">Niveau D'etude: <span class="padding-left">@Model.StudyLevel</span></p>
            <strong>Dernier employeur: <span class="padding-left">@Model.LastJob</span></strong>
        </div>
        <div style="text-align: center">
            <a href="@Model.Resume.Replace("\\", "/")" download>Télécharger CV</a>
            @if (Model.GetExtension().Equals(".pdf", StringComparison.OrdinalIgnoreCase))
            {
                <object data="/@Model.Resume.Replace("\\", "/")" type="application/pdf"></object>
            }
            else
            {
                <img src="/@Model.Resume.Replace("\\", "/")" alt="" />
            }
        </div>
    </div>
</div>

Views/Applications/Applications.cshtml
@{
    ViewData["Title"] = "Condidats";
}

@section styles {
    <link rel="stylesheet" href="~/assets/styles/programs.css" />
    <style>
        .programs .card .card-body a, .delete-button, .primary-button {
            display: inline-block;
            margin: 8px;
            width: auto;
            font-size: 15px;
            padding: 14px
        }

        .delete-application-form {
            display: inline-block
        }

        .search-area {
            width: 100%
        }

        .search-area label {
            display: block;
            font-size: 15px;
            color: #777;
        }

        .search-area .input-button-group {
            display: grid;
            grid-template-columns: 400px 150px;
            grid-gap: 14px;
        }

            .search-area .input-button-group input,
            .search-area .input-button-group input {
                padding: 10px;
                border-radius: 10px;
                border: 1px solid #ccc
            }

        .container.block {
            display: block;
        }

        .text-danger {
            font-size: 14px;
            color: red;
            display: block;
            margin-top: 4px
        }
    </style>
}
@*@model IEnumerable<WeCount.Models.Application>*@
@model WeCount.Data.ViewModels.SearchVM
<div class="programs">
    <div class="container block">
        <form asp-action="SearchApplications" asp-controller="Applications" method="post" class="search-area">
            <label asp-for="SearchText">Search: </label>
            <div class="input-button-group">
                <input asp-for="SearchText" />
                <button type="submit">Search</button>
            </div>
            <span asp-validation-for="SearchText" class="text-danger"></span>
        </form>
        <hr />
    </div>
    <div class="container">
        @foreach (var item in ViewBag.Applications)
        {
            <div class="card">

                @if (item.GetExtension().Equals(".pdf", StringComparison.OrdinalIgnoreCase))
                {
                    <object data="/@item.Resume.Replace("\\", "/")" type="application/pdf"></object>
                }
                else
                {
                    <img src="/@item.Resume.Replace("\\", "/")" alt="" />
                }

                <div class="card-body">
                    <h4 class="card-header">@item.FullName</h4>
                    <strong>Mail: @item.Mail</strong>
                    <strong>Téléphone:  @item.Phone</strong>

                    <strong>
                        Années d’expérience: @item.YearsOfExperinces
                        @if (item.YearsOfExperinces == 1)
                        {
                            <span>Année</span>
                        }
                        else if (item.YearsOfExperinces >= 1)
                        {
                            <span>Années</span>
                        }
                    </strong>

                    <p class="card-text three-lines">Niveau D'etude:  @item.StudyLevel</p>
                    <div>
                        <a class="primary-button" asp-controller="Applications" asp-action="DisplayApplication" asp-route-slag="@item.Slag">Détails</a>
                        <form class="delete-application-form" asp-action="DeleteApplication" asp-controller="Applications" method="post" asp-route-slag="@item.Slag">
                            <button class="delete-button" type="submit">Supprimer</button>
                        </form>
                    </div>
                </div>
            </div>
        }

        @if (ViewBag.Applications.Count == 0)
        {
            <div>No Result Found</div>
        }
    </div>
</div>

@section scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.js"></script>
    <script src="~/assets/scripts/sweetalert2.all.min.js"></script>
    <script>
        const deleteApplicationForms = document.querySelectorAll('.delete-application-form');
        deleteApplicationForms.forEach(form => {
            form.addEventListener('submit', function (e) {
                e.preventDefault();
                Swal.fire({
                    title: 'Tu veux vraiment supprimer ce candidat?',
                    showCancelButton: true,
                    confirmButtonText: 'Supprimer',
                }).then((result) => {
                    if (result.isConfirmed) {
                        e.target.submit();
                    }
                })
            })
        })
    </script>
} 

Views/Applications/Apply.cshtml
@model WeCount.Models.Application
@{
    ViewData["Title"] = "Appliquer";
}

@section styles {
    <link rel="stylesheet" href="~/assets/styles/form.css" />
}

<form method="post" asp-controller="Applications" asp-action="Apply">
    <div class="container">
        <div><strong>• Étape 1 :</strong> Saisie des informations suivantes sur un formulaire</div>
        <br />
        <p>Tous les champs marqués d'un * sont obligatoires</p>
        <div class="column">
            <label asp-for="FirstName">Prénom <span class="required">*</span></label>
            <input type="text" asp-for="FirstName" />
            <span asp-validation-for="FirstName" class="error"></span>

            <label asp-for="LastName">Nom <span class="required">*</span></label>
            <input type="text" asp-for="LastName" />
            <span asp-validation-for="LastName" class="error"></span>

            <label asp-for="Mail">Mail <span class="required">*</span></label>
            <input type="email" asp-for="Mail" />
            <span asp-validation-for="Mail" class="error"></span>

            <label asp-for="Phone">Téléphone <span class="required">*</span></label>
            <input type="text" asp-for="Phone" />
            <span asp-validation-for="Phone" class="error"></span>
        </div>

        <div class="column">
            <label asp-for="StudyLevel">Niveau D'etude <span class="required">*</span></label>
            <select asp-for="StudyLevel">
                <option value="Bac+2">Bac+2</option>
                <option value="Bac+3">Bac+3</option>
                <option value="Bac+4">Bac+4</option>
                <option value="Bac+5">Bac+4</option>
            </select>
            <span asp-validation-for="StudyLevel" class="error"></span>

            <label asp-for="YearsOfExperinces">Nombre d’années d’expérience <span class="required">*</span></label>
            <input type="number" asp-for="YearsOfExperinces" min="0" max="100" />
            <span asp-validation-for="YearsOfExperinces" class="error"></span>

            <label asp-for="LastJob">Dernier employeur <span class="required">*</span></label>
            <input type="text" asp-for="LastJob" />
            <span asp-validation-for="LastJob" class="error"></span>
        </div>
        <div class="column">
            <button class="primary-button" type="submit">Enregistrer <i class="fa fa-save 2x"></i></button>
        </div>
    </div>
</form>

@section scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.js"></script>
} 

Views/Applications/ApplyResume.cshtml
@model WeCount.Data.ViewModels.ResumeVM
@{
    ViewData["Title"] = "Appliquer CV";
}

@section styles {
    <link rel="stylesheet" href="~/assets/styles/form.css" />
}

<form id="main-form" method="post" asp-controller="Applications" asp-action="ApplyResume" enctype="multipart/form-data">
    <div class="container">
        <div><strong>• Étape 1 / Étape 2 :</strong> Uploader le cv du candidat.</div>
        <br />
        <p>Tous les champs marqués d'un * sont obligatoires</p>
        <div class="column">
            <label asp-for="ResumeFile">CV <span class="required">*</span></label>
            <input class="resume-input" type="file" asp-for="ResumeFile" accept="image/*, application/pdf" />
            <span asp-validation-for="ResumeFile" class="error resume-error"></span>
        </div>
        <div class="column">
            <button class="primary-button" type="submit">Enregistrer <i class="fa fa-save 2x"></i></button>
        </div>
    </div>
</form>

@section scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.js"></script>
<script>
    const mainForm = document.getElementById("main-form"),
        resumeInput = document.querySelector(".resume-input"),
        resumeError = document.querySelector(".resume-error");
    mainForm.addEventListener("submit", function (e) {
        var $input = $(resumeInput),
            files = $input[0].files,
            filename = files[0].name,
            extension = filename.substr(filename.lastIndexOf(".")),
            allowedExtensionsRegx = /(\.jpg|\.jpeg|\.png|\.pdf)$/i,
            isAllowed = allowedExtensionsRegx.test(extension);
        if (!isAllowed) {
            resumeError.textContent = "Invalid File Type.";
            e.preventDefault();
        }
    });
</script>
} 

Views/Applications/DisplayApplication.cshtml
@model WeCount.Models.Application

@{
    ViewData["Title"] = "Condidat Détails";
}

@section styles {
    <style>
        .grid {
            display: grid;
            grid-template-columns: 1fr 3fr;
            gap: 8px;
            font-size: 18px
        }

        object, img {
            width: 100%;
            display: block;
            min-height: 600px
        }

        h4 {
            margin: 0;
            padding: 4px 0
        }

        strong {
            font-weight: 600;
            margin: 14px 0;
            color: #1d1c1c;
            display: block;
        }

        p {
            color: var(--grey-color);
            padding: 0;
            margin: 7px 0;
            line-height: 1.4
        }

        .padding-left {
            display: block;
            padding-left: 18px;
        }
    </style>
}

<div class="container content-container">
    <div><strong style="display: inline">• Étape 1 / Étape 2 / Étape 3 :</strong> visualisation du résumé des informations saisies.</div>
    <div class="grid">
        <div>
            <h4>
                Nom:
                <span class="padding-left">@Model.FirstName</span>
            </h4>
            <h4>Préom: <span class="padding-left">@Model.LastName</span></h4>
            <strong>Mail: <span class="padding-left">@Model.Mail</span></strong>
            <strong>Téléphone: <span class="padding-left">@Model.Phone</span></strong>

            <strong>
                Nombre d’années d’expérience:
                <span class="padding-left">
                    @Model.YearsOfExperinces
                @if (Model.YearsOfExperinces == 1)
                {
                    <span>année</span>
                }
                else if (Model.YearsOfExperinces >= 1)
                {
                    <span>années</span>
                }
            </span>
        </strong>

        <p class="card-text three-lines">Niveau D'etude: <span class="padding-left">@Model.StudyLevel</span></p>
        <strong>Dernier employeur: <span class="padding-left">@Model.LastJob</span></strong>
        <div>
            <form class="delete-application-form" asp-action="DeleteApplication" asp-controller="Applications" method="post" asp-route-slag="@Model.Slag">
                <button class="delete-button" type="submit">Supprimer</button>
            </form>
        </div>
    </div>
    <div style="text-align:center">
        <a href="@Model.Resume.Replace("\\", "/")" download>Download CV</a>
        @if (Model.GetExtension().Equals(".pdf", StringComparison.OrdinalIgnoreCase))
        {
            <object data="/@Model.Resume.Replace("\\", "/")" type="application/pdf"></object>
        }
        else
        {
            <img src="/@Model.Resume.Replace("\\", "/")" alt="" />
        }
    </div>
</div>
</div>
@section scripts {
    <script src="~/assets/scripts/sweetalert2.all.min.js"></script>
    <script>
        const deleteApplicationForm = document.querySelector('.delete-application-form');
        deleteApplicationForm.addEventListener('submit', function (e) {
            e.preventDefault();
            Swal.fire({
                title: 'Tu veux vraiment supprimer ce candidat?',
                showCancelButton: true,
                confirmButtonText: 'Supprimer',
            }).then((result) => {
                if (result.isConfirmed) {
                    e.target.submit();
                }
            })
        });
    </script>
} 

Views/Applications/Index.cshtml
@{
    ViewData["Title"] = "Offre D'emploi";
}

@section styles {
    <style>
        .primary-button {
            margin-top: 0
        }

        ul {
            all: revert;
        }
    </style>
}

<div class="container">
    <div class="content-container">
        <h2>Descriptif du poste :</h2>

        <p>Au sein d’une équipe projet fonctionnant en mode collaboratif et Agile scrum, vous serez l’un des développeurs, travaillant en coordination avec le Product-Owner/Proxy Product Owner, le Scrum Master, et équipes partenaires.</p>

        <h3>Dans ce contexte Agile, vous effectuerez différentes tâches :</h3>
        <p>
            L’estimation du niveau d’effort de développement des User stories
            La définition des spécifications détaillées à partir des User stories
            Le développement selon une architecture logicielle établie
            La conduite des tests unitaires et d’intégration 2 à 2
            Participation Le développement des outillages de test associés
            L’automatisation et l’industrialisation des opérations régulières (process de build, les tests, les audits de qualité de code, la containerisation du code, …)
            La préparation des packages de livraison (mode devops)
            Le déploiement sur les environnements d’intégration et de production
            Le support technique et la maintenance corrective et adaptative des éléments délivrés sur les environnements d’intégration et de production
            Vous êtes en relation avec le Product Owner pour gérer le backlog et définir les US
        </p>
        <h3>Profil recherché :</h3>

        <p>
            Vous avez une formation Bac+5 Ingénieur/Master 2 en développement logiciel.
            Vous justifiez d'une expérience de 3 ans minimum dans le développement .Net
            Vous savez présenter une solution disruptive, argumenter, convaincre et travailler dans un environnement complexe
            <br />
            Vous adhérez aux valeurs de l'agilité, et vous maitrisez les outils de gestion agiles et collaboratifs tels que JIRA / Confluence
            <br />
            Vous avez une forte appétence pour le travail en équipe tout en étant autonome et flexible, avec une bonne aisance relationnelle
            <br />
            Vous savez écouter le client et ses utilisateurs, et traduire ses besoins en exigences ou propositions de solution à travers une architecture logicielle adaptée
            <br />
            Vos connaissances dans le domaine des réseaux et Télécom ou « Pricing » seront très appréciées
        </p>
        <h3>Compétences requises :</h3>
        <ul>
            <li>ASP.NET / C# / ASP.NET MVC / Web API / .Net Core</li>
            <li>SOAP / JSON</li>
            <li>JavaScript / Vue.js (or similar)/ jQuery</li>
            <li>HTML / HTML5 / CSS</li>
            <li>Maitrise de l’anglais : écrit/oral</li>
        </ul>
        <h3>Compétences souhaitables :</h3>
        <ul>
            <li>Connaissances SQL/T-SQL/ Microsoft SQL Server</li>
            <li>Connaissances JSON/XML</li>
            <li>Expérience avec UML</li>
            <li>Expérience avec les systèmes de contrôle de version (Git, Team Foundation Server)</li>
            <li>Expérience en Agilité Scrum/Kanban</li>
            <li>Expériences avec Nuget, Owin, Dependency injection, Entity framework, Linq</li>
        </ul>
    </div>
    <br />
    <div><a asp-area="" asp-controller="Applications" asp-action="Apply" class="primary-button">Appliquer <i class="fa fa-arrow-right 2x"></i></a></div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>WeCount - @ViewData["Title"]</title>
    <link rel="icon" href="https://wecount.ma/images/logo.svg" />
    <link rel="stylesheet" href="~/assets/styles/utilities/normalize.css" />
    <link rel="stylesheet" href="~/assets/styles/utilities/utilities.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="crossorigin" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/styles/utilities/font-awesome.min.css" />
    @RenderSection("styles", false)
</head>
<body>
    <header>
        <div class="container">
            <marquee class="info">
                <ul>
                    <li>
                        <i class="fa fa-phone"></i>
                        <div class="content">
                            <strong>+212 – (0) 522 252 965</strong>
                            <strong>+212 – (0) 522 252 965</strong>
                        </div>
                    </li>
                    <li>
                        <i class="fa fa-envelope-square"></i>
                        <div class="content"><strong>hello@wecount.ma</strong></div>
                    </li>
                    <li>
                        <i class="fa fa-clock-o"></i>
                        <div class="content"><strong>Monday To Friday</strong><strong>9:00 – 18:00</strong></div>
                    </li>
                </ul>
            </marquee>
            <ul class="socials">
                <li><a href="#"><i class="fa fa-facebook-square fa-2x" data-social="facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter-square fa-2x" data-social="twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus-square fa-2x" data-social="google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin-square fa-2x" data-social="linkedin"></i></a></li>
            </ul>
        </div>
    </header>
    <nav>
        <div class="container">
            <h1><a asp-area="" asp-controller="Applications" asp-action="Index"><img src="https://wecount.ma/images/logo.svg" /></a></h1>
            <div class="toggle-button"><i class="fa fa-bars"></i></div>
            <ul class="links">
                <li><a asp-area="" asp-controller="Applications" asp-action="Index">Page d'accueil</a></li>
                <li><a asp-area="" asp-controller="Applications" asp-action="Applications">Candidats</a></li>
            </ul>
        </div>
    </nav>
    <main role="main">
        <div class="landing-page">
            <div class="overlay"></div>
            <div class="container">
                <h2>@ViewData["Title"]</h2>
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo et culpa quia voluptatem temporibus. Harum mollitia rerum laboriosam inventore sequi non nam natus, amet veniam, voluptate iste voluptatem maxime autem quidem! Nulla nisi vero quidem distinctio perspiciatis esse, nostrum architecto molestiae eveniet magni facilis!
                    <br />
                    amet veniam, voluptate iste voluptatem maxime autem quidem! Nulla nisi vero quidem distinctio perspiciatis esse, nostrum architecto molestiae eveniet magni facilis.
                </p>
            </div>
        </div>
        @RenderBody()
    </main>

    <footer>
        <div class="container">
            <span>&copy; Copyright WeCount <br /> All Rights Reserved</span>
            <ul class="socials">
                <li><a href="#"><i class="fa fa-facebook-square fa-2x" data-social="facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter-square fa-2x" data-social="twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus-square fa-2x" data-social="google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin-square fa-2x" data-social="linkedin"></i></a></li>
            </ul>
        </div>
    </footer>
    <script src="~/assets/scripts/script.js"></script>
    @RenderSection("scripts", false)
</body>
</html>